### ISSUE TITLE
pi-scan crashes at first "Generating Preview" step

### ISSUE THREAD

**Issue by narrowdogs** [Tenrec-Builders/pi-scan#1]
I have a raspberry Pi model B+ V1.2
Two Canon A2500 cameras
I have a thumb drive plugged into the Pi, plus the 2 cameras and a USB keyboard: nothing else connected.

I downloaded pi-scan-1.0-mouse.img from the link:
Raspberry Pi Image (for mouse) 

Wrote the image onto the ssd for the Pi, tried running the software, everything seems fine util it gets to Refocus, I press 3, I hear the cameras take photos, then it gets to generating previews and it locks up, then restarts piscan.

I have tried updating the cards for the cameras: no change, I changed thumb drive: no change.

I am a bit ignorant on how to send you debug files, if you can give me some hints, I'll gladly send them.

**Comment by duerig** [comment]
Alas, Pi Scan needs the extra memory from a Pi 2 or a Pi 3. So it is
running out of memory when trying to generate a preview for you. I need
to add a more friendly way of detecting and reporting to the user when
they try to run it on an older Pi.
 
 
On Sun, Jun 19, 2016, at 03:29 PM, narrowdogs wrote:
> I have a raspberry Pi model B+ V1.2
>  Two Canon A2500 cameras
>  I have a thumb drive plugged into the Pi, plus the 2 cameras and a
>  USB keyboard: nothing else connected.
> I downloaded pi-scan-1.0-mouse.img from the link:
>  Raspberry Pi Image (for mouse)
> Wrote the image onto the ssd for the Pi, tried running the software,
> everything seems fine util it gets to Refocus, I press 3, I hear the
> cameras take photos, then it gets to generating previews and it locks
> up, then restarts piscan.
> I have tried updating the cards for the cameras: no change, I changed
> thumb drive: no change.
> I am a bit ignorant on how to send you debug files, if you can give me
> some hints, I'll gladly send them.
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
>
 

Links:

  1. https://github.com/Tenrec-Builders/pi-scan/issues/1
  2. https://github.com/notifications/unsubscribe/AA1sTHwjrTMo0fA8_2ORvhjm7vsc1IpHks5qNbSggaJpZM4I5Qaz

**Comment by narrowdogs** [comment]
Ah, I didn't realize that. I shall order a new Pi forthwith ( nice that the computer is an infinitessimal cost :-))
