### ISSUE TITLE
Status of pi-scan project

### ISSUE THREAD

**Issue by decentral1se** [Tenrec-Builders/pi-scan#19]
Hey folks, thanks for this wonderful work! I see that the last commit to the project was "22 Mar 2018" and that the `#diybookscanner` channel on freenode (somewhat related?) is empty, so I am wondering what is the status of the project? I am starting to work with pi-scan and a built scanner and want have a background in software, so I want to see if I can also help co-maintain the pi-scan project to ensure it stays up to date and can progress with the raspberry pi / debian / python etc. moving ecosytems.

**Comment by duerig** [comment]
The best place to talk about this is at the DIY Book Scanner forums: https://forum.diybookscanner.org/

This is a dormant project in that it is working and I am not actively adding features. It is not dead, though, and to the extent that I find more features to add or others want to add features it can become more active. The next update I will make will be support for the new Raspberry Pi 4 which was released recently, and some improvements to stability. If you have other priorities or other parts you want to work on, feel free to post in the forum or email me.

**Comment by decentral1se** [comment]
Thanks a lot for the update <3
