### ISSUE TITLE
can't get Pi Scan to start

### ISSUE THREAD

**Issue by jhub95** [Tenrec-Builders/pi-scan#8]
Hi there. Downloaded most recent mouse version today (Sept 19, 2017). When booting up the Pi 3 model B I get an error screen that keeps looping.

> File "main.py", line 14, in <module>
> import wiringpi
> ImportError: No module named wiringpi

It says it saved a log to /home/pi/.kivy/logs but I don't see that log file

The same error happens whether I have a keyboard and mouse plugged in or not.
![img_20170919_112852686](https://user-images.githubusercontent.com/7361909/30585796-a103deba-9d36-11e7-985d-fd170020e1c7.jpg)

**Comment by duerig** [comment]
It looks like you downloaded the 'mouse' version. I will rebuild that image and upload it with a fix.

In the mean time, a workaround is to download the 'touch' version. I know that people have used that successfully. On the 'touch' version, the mouse cursor doesn't show. But you can control Pi Scan entirely with a keyboard.

Alternatively, the only difference between these two images is supposed to be the file .kivy/config.ini. If the mouse version is broken at this time, then you can make your own mouse version from the touch version:

(1) Download and run the 'touch' version

(2) Alt-F2 to switch to another console.

(3) Log in username 'pi' password 'raspberry'

   sudo mount -o remount,rw /
   sudo nano /home_org/pi/.kivy/config.ini

(4) Modify the config.ini to match the mouse config file:

https://github.com/Tenrec-Builders/pi-scan/blob/master/config/mouse.ini

(5) Reboot pi: `sudo reboot`

That should permanently change the touch image into a mouse image.

In the mean time, I'll be building a new image and testing it out. Sorry about the mistake.

**Comment by jhub95** [comment]
Thanks, Jonathon.  After following your instructions above it now boots. Thanks!

**Comment by artelse** [comment]
Got the same issue. Would be great if the mouse version would be updated and linked on the home page.

**Comment by duerig** [comment]
A new and fixed build has been uploaded. I apologize for the delay. Let me know if it works.
